---
- name: Nginx playbook
  hosts: app01
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Copiar index.html
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
      owner: root
      group: root
      mode: '0644'

  - name: Reiniciar Nginx
    service:
      name: nginx
      state: restarted
